// flipkart amazon jaise ek item ka catalogue or uske neeche 3 uski choti choti images jinpe click karne pr wo badi img me convert ho jaye

let firstbox=()=>{
 let name=document.querySelector(".main")
  // name.style.backgroundColor="red"
  name.style.border="2px solid black"
  name.style.backgroundImage="url('https://tse2.mm.bing.net/th?id=OIP.Fpy5vE4DAZIUu260YkORKwHaEK&pid=Api&P=0&h=180')"
    name.style.backgroundSize="cover"
}
let secondbox=()=>{
 let name=document.querySelector(".main")
  // name.style.color="blue"
  // name.style.backgroundColor="blue"
  name.style.border="2px solid black"
  name.style.backgroundImage=" url('https://tse3.mm.bing.net/th?id=OIP.LMMfNeXMfBbCD8MgBaM8ewHaEK&pid=Api&P=0&h=180')"
  name.style.backgroundSize="cover"
}
// let thirdbox=()=>{
//  let name=document.querySelector(".main")
// //   name.style.backgroundColor="white"
//   name.style.border="2px solid black"

//     name.style.backgroundImage=" url('https://tse3.mm.bing.net/th?id=OIP._xBTtmYvWgLHbYDbEX276wHaEK&pid=Api&P=0&h=180')"
//     name.style.backgroundSize="cover"

// }

